openapi: 3.0.0
info:
  title: uasocks
  version: 1.0.0
servers:
  - url: https://uasocks-backend.local
  - url: https://api.proxcet.io
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    apikeyAuth:
      type: http
      scheme: apikey
tags:
  - name: Auth
  - name: Proxcet
  - name: Account
paths:
  /api/{locale}/login:
    post:
      tags:
        - Auth
      summary: login
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: email@com
                password:
                  type: string
                  example: password2
      parameters:
        - name: locale
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/{locale}/register:
    post:
      tags:
        - Auth
      summary: register
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: email22@com
                password:
                  type: string
                  example: password
      parameters:
        - name: locale
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/{locale}/forgot-password:
    post:
      tags:
        - Auth
      summary: forgot-password
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: email@com
      parameters:
        - name: locale
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/{locale}/resending-verify:
    post:
      tags:
        - Auth
      summary: resending-verify
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: email@com
      parameters:
        - name: locale
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/{locale}/verify/1/3SvpdPKj:
    get:
      tags:
        - Auth
      summary: verify
      parameters:
        - name: locale
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/{locale}/refresh:
    post:
      tags:
        - Auth
      summary: refresh
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Test
                email:
                  type: string
                  example: email@com
                password:
                  type: string
                  example: password
      parameters:
        - name: locale
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/{locale}/destroy:
    post:
      tags:
        - Auth
      summary: destroy
      requestBody:
        content: {}
      parameters:
        - name: locale
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/{locale}/logout:
    post:
      tags:
        - Auth
      summary: logout
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Test
                email:
                  type: string
                  example: email@com
                password:
                  type: string
                  example: password
      security:
        - bearerAuth: []
      parameters:
        - name: locale
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/client:
    post:
      tags:
        - Proxcet
      summary: add client
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: test0005
                password: '11111111'
                readLimit: null
                writeLimit: null
                connectionLimit: null
                changeIpUid: kwUgib8fGd
                tags:
                  - key: userId
                    value: '1'
                changeIpDelaySec: null
                agentId: 78e55e84-6aea-42a9-ac7c-df7a3c915094
                os: Default
      security:
        - apikeyAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Proxcet
      summary: list clients
      security:
        - apikeyAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/agent:
    get:
      tags:
        - Proxcet
      summary: list agents
      security:
        - apikeyAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/{locale}/list-proxy:
    get:
      tags:
        - Account
      summary: list-proxy
      security:
        - bearerAuth: []
      parameters:
        - name: locale
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/{locale}/up-proxy:
    put:
      tags:
        - Account
      summary: up-proxy
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: 4302cb96-a05e-4309-9891-f76996f7a2aa
                username: test0007
                password: AGbyM7jo
                readLimit: null
                writeLimit: null
                connectionLimit: 600
                changeIpUid: Z21fTCU7NL
                tags:
                  - key: userId
                    value: '1'
                  - key: proxy_group
                    value: kyivstar
                changeIpDelaySec: null
                agentId: b7a9d5b4-cc25-48dc-b5c7-e96606153152
                os: Default
      security:
        - bearerAuth: []
      parameters:
        - name: locale
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/{locale}/add-proxy:
    post:
      tags:
        - Account
      summary: add-proxy
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: test0005
                password: wEw3VYgn
                readLimit: null
                writeLimit: null
                connectionLimit: null
                changeIpUid: Lb5HzfRKQJ
                tags:
                  - key: userId
                    value: '1'
                  - key: proxy_group
                    value: vodafone
                changeIpDelaySec: null
                agentId: b7a9d5b4-cc25-48dc-b5c7-e96606153152
                os: Default
      security:
        - bearerAuth: []
      parameters:
        - name: locale
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/{locale}/settings:
    get:
      tags:
        - Account
      summary: settings
      security:
        - bearerAuth: []
      parameters:
        - name: locale
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/{locale}/reset-password:
    put:
      tags:
        - Account
      summary: reset-password
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                email:
                  type: string
                  example: email@com
                old_password:
                  type: string
                  example: password1
                password:
                  type: string
                  example: password2
                password_confirmation:
                  type: string
                  example: password2
      security:
        - bearerAuth: []
      parameters:
        - name: locale
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/{locale}/add-telegram:
    put:
      tags:
        - Account
      summary: add-telegram
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                nickname_telegram:
                  type: string
                  example: test1
      security:
        - bearerAuth: []
      parameters:
        - name: locale
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/{locale}/up-telegram:
    put:
      tags:
        - Account
      summary: up-telegram
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                nickname_telegram:
                  type: string
                  example: test2
      security:
        - bearerAuth: []
      parameters:
        - name: locale
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/{locale}/reset-email:
    put:
      tags:
        - Account
      summary: reset-email
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                email:
                  type: string
                  example: email@com
                password:
                  type: string
                  example: password2
                old_email:
                  type: string
                  example: email100@com
      security:
        - bearerAuth: []
      parameters:
        - name: locale
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/{locale}/home:
    get:
      tags:
        - General
      summary: home
      parameters:
        - name: locale
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
